stages:
- name: Step1
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: app:v1
      pushRemote: true
      registry: 10.43.67.82:5000
- name: Step2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
