stages:
- name: Stage1
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: teste:${CICD_EXECUTION_SEQUENCE}
- name: Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      event:
        include:
        - push
timeout: 60
notification: {}
