stages:
- name: Publish - Landing
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
      registry: 10.43.168.236
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
  when:
    branch:
      include:
      - main
- name: Deployment - Landing
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch:
      include:
      - main
notification: {}
