stages:
- name: Stage2
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-landing:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34520
- name: Stage2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
