stages:
- name: Stage1
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example:v1
      registry: 127.0.0.1:34228
- name: Stage2
  steps:
  - applyAppConfig:
      catalogTemplate: example
      version: v1
      name: testeApp
      targetNamespace: ped
timeout: 60
notification: {}
