stages:
- name: Publish - Landing
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-landing:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.0.6.220:30000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
  when:
    branch:
      include:
      - main
- name: Deployment - Landing
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch:
      include:
      - main
notification: {}
