stages:
- name: Stepe1
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-landing:v1
- name: Stepe2
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
