stages:
- name: Publish - Landing
  when:
    branch: main
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-landing:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
- name: Deployment - Landing
  when:
    branch: main
  steps:
    - applyYamlConfig:
        path: ./deployment.yaml
- name: Ingress - Landing
  when:
    branch: main
  steps:
    - applyYamlConfig:
        path: ./ingress.yaml
