kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  selector:
    app: app-teste
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-helloserver
  labels:
    app: app-teste
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-teste
  template:
    metadata:
      labels:
        app: app-teste
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: teste
        image: teste:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
