apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-landing
spec:
  selector:
    matchLabels:
      app: my-landing
  template:
    metadata:
      labels:
        app: my-landing
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - name: my-landing
        image: 127.0.0.1:34228/my-landing:${CICD_EXECUTION_SEQUENCE}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-landing-svc
spec:
  selector:
    app: my-landing
  ports:
  - port: 80
    targetPort: 80
